version: '3.9'

services:
    web:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./config/default.conf:/etc/nginx/conf.d/default.conf

    clean-arch:
        build:
            context: ./config
        container_name: clean-arch
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"